version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
  db:
    image: postgres:11
    ports:
      - 32700:5432
    volumes:
      - ./src/database_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER:  root
      POSTGRES_PASSWORD:  root
      POSTGRES_DB: shop